tournament_name = "Big Funny Cup VIII: Dead Cup Edition"
season_num = 3
date = 2025-11-29
has_losers = false
playoff_teams = 8

##################### HEAD TO HEAD ####################

[[head_to_head]]
team = "FC Fine Dining"
decider_points = 1

[[head_to_head]]
team = "Alpha Space Bros"
decider_points = 0

####################### GROUP A #######################

#1
[[brackets.groups]]
group_id = "A"
team1 = "FC Fine Dining"
score1 = 1
team2 = "Autoism"
score2 = 1

#2
[[brackets.groups]]
group_id = "A"
team1 = "Bone Zone"
score1 = 3
team2 = "Moai"
score2 = 1

#3
[[brackets.groups]]
group_id = "A"
team1 = "FC Fine Dining"
score1 = 0
team2 = "Bone Zone"
score2 = 1

#4
[[brackets.groups]]
group_id = "A"
team1 = "Autoism"
score1 = 2
team2 = "Moai"
score2 = 1

#5
[[brackets.groups]]
group_id = "A"
team1 = "FC Fine Dining"
score1 = 1
team2 = "Moai"
score2 = 3

#6
[[brackets.groups]]
group_id = "A"
team1 = "Autoism"
score1 = 2
team2 = "Bone Zone"
score2 = 1

####################### GROUP B #######################

#1
[[brackets.groups]]
group_id = "B"
team1 = "Disney"
score1 = 2
team2 = "Fink Ployd"
score2 = 4

#2
[[brackets.groups]]
group_id = "B"
team1 = "The Dump"
score1 = 2
team2 = "Gambit"
score2 = 0

#3
[[brackets.groups]]
group_id = "B"
team1 = "Disney"
score1 = 1
team2 = "The Dump"
score2 = 2

#4
[[brackets.groups]]
group_id = "B"
team1 = "Fink Ployd"
score1 = 0
team2 = "Gambit"
score2 = 0

#5
[[brackets.groups]]
group_id = "B"
team1 = "Disney"
score1 = 1
team2 = "Gambit"
score2 = 2

#6
[[brackets.groups]]
group_id = "B"
team1 = "Fink Ployd"
score1 = 1
team2 = "The Dump"
score2 = 0

####################### GROUP C #######################

#1
[[brackets.groups]]
group_id = "C"
team1 = "Big Funky"
score1 = 0
team2 = "The Chairs"
score2 = 0

#2
[[brackets.groups]]
group_id = "C"
team1 = "Nintendont"
score1 = 0
team2 = "Vidya"
score2 = 1

#3
[[brackets.groups]]
group_id = "C"
team1 = "Big Funky"
score1 = 0
team2 = "Nintendont"
score2 = 3

#4
[[brackets.groups]]
group_id = "C"
team1 = "The Chairs"
score1 = 1
team2 = "Vidya"
score2 = 0

#5
[[brackets.groups]]
group_id = "C"
team1 = "Big Funky"
score1 = 2
team2 = "Vidya"
score2 = 1

#6
[[brackets.groups]]
group_id = "C"
team1 = "The Chairs"
score1 = 0
team2 = "Nintendont"
score2 = 0

####################### GROUP D #######################

#1
[[brackets.groups]]
group_id = "D"
team1 = "Alpha Space Bros"
score1 = 1
team2 = "Cursed"
score2 = 3

#2
[[brackets.groups]]
group_id = "D"
team1 = "Cartoons FC"
score1 = 0
team2 = "HmX Gaming"
score2 = 1

#3
[[brackets.groups]]
group_id = "D"
team1 = "Alpha Space Bros"
score1 = 1
team2 = "Cartoons FC"
score2 = 1

#4
[[brackets.groups]]
group_id = "D"
team1 = "Cursed"
score1 = 0
team2 = "HmX Gaming"
score2 = 1

#5
[[brackets.groups]]
group_id = "D"
team1 = "Alpha Space Bros"
score1 = 0
team2 = "HmX Gaming"
score2 = 1

#6
[[brackets.groups]]
group_id = "D"
team1 = "Cursed"
score1 = 1
team2 = "Cartoons FC"
score2 = 1

###################### WINNERS ######################

#1
[[brackets.winners]]
team1 = "Autoism"
score1 = 2
team2 = "The Dump"
score2 = 0

#2
[[brackets.winners]]
team1 = "Nintendont"
score1 = 2
team2 = "HmX Gaming"
score2 = 0

#3
[[brackets.winners]]
team1 = "The Chairs"
score1 = 1
team2 = "Cursed"
score2 = 3

#4
[[brackets.winners]]
team1 = "Bone Zone"
score1 = 2
team2 = "Fink Ployd"
score2 = 0

#5
[[brackets.winners]]
team1 = "Autoism"
score1 = 0
team2 = "Nintendont"
score2 = 3

#6
[[brackets.winners]]
team1 = "Cursed"
score1 = 2
team2 = "Bone Zone"
score2 = 1

#7 â€“ FINAL
[[brackets.winners]]
team1 = "Nintendont"
score1 = 1
team2 = "Cursed"
score2 = 2
