tournament_name = "Big Funny Cup VII: Aeiou Edition"
season_num = 2
date = 2024-07-06
has_losers = false
playoff_teams = 8

####################### GROUP A #######################

#1
[[brackets.groups]]
group_id = "A"
team1 = "Alpha Space Bros"
score1 = 2
team2 = "The Chairs"
score2 = 1

#2
[[brackets.groups]]
group_id = "A"
team1 = "Fink Ployd"
score1 = 0
team2 = "Vidya"
score2 = 0

#3
[[brackets.groups]]
group_id = "A"
team1 = "Alpha Space Bros"
score1 = 0
team2 = "Fink Ployd"
score2 = 0

#4
[[brackets.groups]]
group_id = "A"
team1 = "The Chairs"
score1 = 1
team2 = "Vidya"
score2 = 1

#5
[[brackets.groups]]
group_id = "A"
team1 = "Alpha Space Bros"
score1 = 1
team2 = "Vidya"
score2 = 0

#6
[[brackets.groups]]
group_id = "A"
team1 = "The Chairs"
score1 = 1
team2 = "Fink Ployd"
score2 = 0


####################### GROUP B #######################

#1
[[brackets.groups]]
group_id = "B"
team1 = "Cartoons FC"
score1 = 3
team2 = "Big Funky"
score2 = 0

#2
[[brackets.groups]]
group_id = "B"
team1 = "Bone Zone"
score1 = 2
team2 = "Moai"
score2 = 1

#3
[[brackets.groups]]
group_id = "B"
team1 = "Cartoons FC"
score1 = 2
team2 = "Bone Zone"
score2 = 2

#4
[[brackets.groups]]
group_id = "B"
team1 = "Big Funky"
score1 = 0
team2 = "Moai"
score2 = 0

#5
[[brackets.groups]]
group_id = "B"
team1 = "Cartoons FC"
score1 = 4
team2 = "Moai"
score2 = 0

#6
[[brackets.groups]]
group_id = "B"
team1 = "Big Funky"
score1 = 1
team2 = "Bone Zone"
score2 = 2

####################### GROUP C #######################

#1
[[brackets.groups]]
group_id = "C"
team1 = "Gambit"
score1 = 0
team2 = "Nintendont"
score2 = 1

#2
[[brackets.groups]]
group_id = "C"
team1 = "HmX Gaming"
score1 = 1
team2 = "FC Fine Dining"
score2 = 2

#3
[[brackets.groups]]
group_id = "C"
team1 = "Gambit"
score1 = 0
team2 = "HmX Gaming"
score2 = 1

#4
[[brackets.groups]]
group_id = "C"
team1 = "Nintendont"
score1 = 1
team2 = "FC Fine Dining"
score2 = 2

#5
[[brackets.groups]]
group_id = "C"
team1 = "Gambit"
score1 = 1
team2 = "FC Fine Dining"
score2 = 1

#6
[[brackets.groups]]
group_id = "C"
team1 = "Nintendont"
score1 = 2
team2 = "HmX Gaming"
score2 = 1

####################### GROUP D #######################

#1
[[brackets.groups]]
group_id = "D"
team1 = "Disney"
score1 = 3
team2 = "The Dump"
score2 = 0

#2
[[brackets.groups]]
group_id = "D"
team1 = "Autoism"
score1 = 1
team2 = "Cursed"
score2 = 1

#3
[[brackets.groups]]
group_id = "D"
team1 = "Disney"
score1 = 2
team2 = "Autoism"
score2 = 1

#4
[[brackets.groups]]
group_id = "D"
team1 = "The Dump"
score1 = 0
team2 = "Cursed"
score2 = 2

#5
[[brackets.groups]]
group_id = "D"
team1 = "Disney"
score1 = 1
team2 = "Cursed"
score2 = 0

#6
[[brackets.groups]]
group_id = "D"
team1 = "The Dump"
score1 = 1
team2 = "Autoism"
score2 = 0

###################### WINNERS ######################

#1
[[brackets.winners]]
team1 = "Alpha Space Bros"
score1 = 3
pen1 = 1
team2 = "Bone Zone"
score2 = 3
pen2 = 3

#2
[[brackets.winners]]
team1 = "Nintendont"
score1 = 0
team2 = "Disney"
score2 = 1

#3
[[brackets.winners]]
team1 = "FC Fine Dining"
score1 = 1
team2 = "Cursed"
score2 = 0

#4
[[brackets.winners]]
team1 = "The Chairs"
score1 = 4
team2 = "Cartoons FC"
score2 = 6

#5
[[brackets.winners]]
team1 = "Bone Zone"
score1 = 2
team2 = "Disney"
score2 = 3

#6
[[brackets.winners]]
team1 = "FC Fine Dining"
score1 = 3
team2 = "Cartoons FC"
score2 = 0

#7 â€“ FINAL
[[brackets.winners]]
team1 = "Disney"
score1 = 3
team2 = "FC Fine Dining"
score2 = 4
